# Run zeta0
zeta0: serialzeta.cpp
	g++ serialzeta.cpp -o zeta0
	./zeta0

# Run utest
utest: unittestzeta.cpp
	g++ unittestzeta.cpp -o utestzeta0
	./utestzeta0

# Run vtest
vtest: verificationzeta.cpp
	g++ verificationzeta.cpp -o vtestzeta0
	./vtestzeta0
